### ISSUE TITLE
Web Build?

### ISSUE THREAD

**Issue by lishaduck** [infinityJKA/Mana-Cycle#7]
Could there be a mirror of the Itch page on GitHub Pages? Securly still blocks Itch's CDN, so the latest versions are unplayable. Alternatively, you could package for Mac, but getting that notarized and such would most likely be more hassle than it's worth. Typical Apple. I'd build it myself, but IT had us use Godot this year instead of Unity 😞. The old deployment at <https://three-halves.github.io/Mana-Cycle-Web-Build/> still works, but it's pretty outdated.
Thanks!

**Comment by jackachulian** [comment]
@three-halves could you do this? should be able to just take the file on itch.io, download it and put it on your github pages

**Comment by lishaduck** [comment]
> Newest mirror at https://three-halves.github.io/Mana-Cycle-Web-Build/ now reflects the newest version.

Thank you!
